version: "3.8"
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo_database
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "6432:5432"

  todo_backend:
    build: ./backend
    image: todo-app
    container_name: todo_api

    ports:
      - "8080:8080"

    depends_on:
      - db

  todo_frontend:
    build: ./frontend
    image: todo-app-front
    container_name: todo_front

    ports:
      - "5173:5173"

    depends_on:
      - todo_backend
